@eventId = 039dbea3-a1e1-4c48-a82a-f7c5fbe13a82

###

GET http://localhost:3000/events

###

GET http://localhost:3000/events/{{eventId}}

###
# @name create_event
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "My Event",
    "description": "This is a really nice event",
    "date": "2022-01-01T00:00:00",
    "price": 100.0
}


###

PATCH http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
    "name": "My Event renamed",
    "description": "This is a really nice event",
    "date": "2022-01-01T00:00:00",
    "price": 100.0
}

###

DELETE http://localhost:3000/events/{{eventId}}

###

GET http://localhost:3000/events/{{eventId}}

###

GET http://localhost:3000/events/{{eventId}}/spots

###
# @name create_event
POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
    "name": "A4"
}


###

PATCH http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json
X-Api-Token: 123

{
    "name": "A1"
}

###

DELETE http://localhost:3000/events/{{eventId}}/spots


###
POST http://localhost:3000/events/{{eventId}}/reserve
Content-Type: application/json
X-Api-Token: 123

{
    "spots": ["A4"],
    "ticket_kind": "full",
    "email": "carlos.oe.cc@gmail.com"
}