@eventId = 906c0731-72dc-4d54-bb68-55df53be98a5

###

GET http://localhost:3000/events

###

GET http://localhost:3000/events/{{eventId}}

###
# @name create_event
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "My Event",
    "description": "This is a really nice event",
    "date": "2022-01-01T00:00:00",
    "price": 100.0
}


###

PATCH http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
    "name": "My Event renamed",
    "description": "This is a really nice event",
    "date": "2022-01-01T00:00:00",
    "price": 100.0
}

###

DELETE http://localhost:3000/events/{{eventId}}

###

GET http://localhost:3000/events/{{eventId}}

###

GET http://localhost:3000/events/{{eventId}}/spots

###
# @name create_event
POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
    "name": "A11"
}


###

PATCH http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
    "name": "B1"
}

###

DELETE http://localhost:3000/events/{{eventId}}/spots


###
POST http://localhost:3000/events/{{eventId}}/reserve
Content-Type: application/json

{
    "spots": ["A11"],
    "ticket_kind": "full",
    "email": "carlos.oe.cc@gmail.com"
}